version: '3.8'

services:
  toedirs:
    build:
      dockerfile: Dockerfile.musl

    volumes:
      - .:/app:cached

    ports:
    - "8479:8479"

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    environment:
      # DB_USER: toedi
      # DB_NAME: toedi
      # DB_PASSWORD: toedi
      # DB_HOST: db
      DATABASE_URL: postgres://toedi:toedi@db:5432/toedi
      LEPTOS_SITE_ADDR: 0.0.0.0:8479
      LEPTOS_SITE_ROOT: /site
      PROFILE: release

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: toedi
      POSTGRES_DB: toedi
      POSTGRES_PASSWORD: toedi
    ports:
    - "5432:5432"

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
