version: '3.8'

services:
  toedirs:
    image: panaetius123/toedirs:latest
    ports:
    - "8479:8479"

    environment:
      # change this to match username/password in postgres container
      DATABASE_URL: postgres://toedi:toedi@db:5432/toedi
      LEPTOS_SITE_ADDR: 0.0.0.0:8479
      LEPTOS_SITE_ROOT: /site
      PROFILE: release
    networks:
      - toedirs_internal
      - toedirs_public

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: toedi
      POSTGRES_DB: toedi
      # change password
      POSTGRES_PASSWORD: toedi
    networks:
      - toedirs_internal
volumes:
  postgres-data:
networks:
  toedirs_internal:
    internal: true
  toedirs_public:
