name: Run Tests
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fmt:
    name: Leptosfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-04-04
          targets: wasm32-unknown-unknown,x86_64-unknown-linux-gnu
      - name: install leptos
        run: cargo install --locked leptosfmt 
      - name: enforce formatting
        run: leptosfmt --check src
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
          toolchain: nightly-2024-04-04
          targets: wasm32-unknown-unknown,x86_64-unknown-linux-gnu
      - name: check clippy
        run: cargo clippy -- -D warnings
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [fmt, clippy]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-04-04
          targets: wasm32-unknown-unknown,x86_64-unknown-linux-gnu
      - name: install leptos
        run: cargo install --locked cargo-leptos
      - name: run tests
        run: cargo leptos test      
  end2end:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: [test]
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-04-04
          targets: wasm32-unknown-unknown,x86_64-unknown-linux-gnu
      - name: install leptos
        run: cargo install --locked cargo-leptos
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          cd end2end
          npm ci
      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps
          cd ..
      - name: run end2end tests
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
        run: cargo leptos end-to-end      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
